name: boston_analytics_example
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- openssl=1.0.2j
- pip=9.0.1
- python=3.6.0
# - readline=6.2=2
- setuptools=27.2.0
- sqlite=3.13.0
- tk=8.5.18
# - unixodbc=2.3.4=0
- wheel=0.29.0
# - xz=5.2.2=1
- zlib=1.2.8
- pip:
  - amqp==2.1.4
  - appnope==0.1.0
  - arrow==0.10.0
  - attrs==16.3.0
  - bleach==1.5.0
  - cerberus==1.0.1
  - decorator==4.0.11
  - entrypoints==0.2.2
  - html5lib==0.9999999
  - hypothesis==3.6.1
  - ipykernel==4.5.2
  - ipython==5.2.2
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.9.5
  - jsonpickle==0.9.4
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - kombu==4.0.2
  - markupsafe==0.23
  - mistune==0.7.3
  - nbconvert==5.1.1
  - nbformat==4.3.0
  - notebook==4.4.1
  - numpy==1.12.0
  - pandas==0.19.2
  - pandocfilters==1.4.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.13
  - ptyprocess==0.5.1
  - pyaml==16.12.2
  - pygments==2.2.0
  - pyodbc==4.0.11
  - python-dateutil==2.6.0
  - pytz==2016.10
  - pyyaml==3.12
  - pyzmq==16.0.2
  - qtconsole==4.2.1
  - requests==2.12.4
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - testpath==0.3
  - tornado==4.4.2
  - traitlets==4.3.1
  - vine==1.1.3
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6

